### ISSUE TITLE
Create a CHANGELOG.md!

### ISSUE THREAD

**Issue by warp9pnt9** [Munawwar/flex-helper#3]
The [Keep a Changelog](http://keepachangelog.com/) project outlines the reasons and best practices.  One thing as yet unmentioned in the project but which seems universally useful would be a "KNOWN ISSUES" section, if there are any known issues that either don't yet have, or can never have a proper resolution.

**Comment by Munawwar** [comment]
Will do.

As for known issues, all of the flexbox bugs are documented at https://github.com/philipwalton/flexbugs.

However I haven't bumped into all of them, since this project only uses a subset of the flexbox specification.
The one that I did see is the min-height problem on IE 10-11 mentioned in the README. IE 10-11 needs a specified CSS 'height'.

**Comment by warp9pnt9** [comment]
Noted, and thanks for the reference!

**Comment by Munawwar** [comment]
Changelog created.
